### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by MTRNord** [libremonde-org/paper-research-privacy-matrix.org#3]
Possibly relevant for future visitors is that some of these things are based on outdated information. For example identity servers can be selfhosted these days and even aren't really needed anymore unless you want to search by phone number.

Also the reference implementation keyword was dropped by both element (previously riot) and Synapse.

Also not that matrix is far more diverse than matrix.org or element (previously new vector).

You can choose a community homeserver implementation (conduit or construct) and plenty of foss community made clients like nheko or fluffychat.

**Comment by maxidorius** [comment]
I have added [a notice](https://github.com/libremonde-org/paper-research-privacy-matrix.org/commit/dfae4dbb53e46ca26b17b1b1553c2d075e351c95) for people who still end up on those papers, making sure they use their own judgement to evaluate the accuracy of these papers and how well they pass the test of time.

As for your comments:
---
> For example identity servers can be selfhosted these days and even aren't really needed anymore unless you want to search by phone number.

The papers never said they couldn't be self-hosted, only that people were led to believe they couldn't or didn't need to.   
Search by phone number always has been the point of using them, thanks for confirming this is not outdated and still accurate.

---

> Also the reference implementation keyword was dropped by both element (previously riot) and Synapse.

The paper is clear, section [Closing words](https://github.com/libremonde-org/paper-research-privacy-matrix.org/blob/master/part1/README.md#closing-words) of Part 1:
> Matrix.org makes a promise of a secure and self-contained protocol while promoting privacy. But at the same time, has a near-monopol in the whole ecosystem in terms of client and server use: Riot and synapse, also labelled "reference implementations"

You can see a capture of the matrix.org website as of writing this reply ([Wayback Machine link for posterity](https://web.archive.org/web/20230410204653/https://matrix.org/)):
![image](https://user-images.githubusercontent.com/10545559/230995972-26bbd1f3-25c1-4e80-b1f2-0e0895856ca2.png)
With the reference implementations link pointing to the matrix.org github repos:
![image](https://user-images.githubusercontent.com/10545559/230996061-2b822caf-701b-40f2-8df2-7f8b10abbb95.png)
[Wayback machine](https://web.archive.org/web/20211102225440/https://matrix.org/) tells us nothing changed on the matrix.org website. Seems accurate enough to me.

---

> Also not that matrix is far more diverse than matrix.org or element (previously new vector).
> You can choose a community homeserver implementation (conduit or construct) and plenty of foss community made clients like nheko or fluffychat.

Correct, which was also true back then. Matrix has always been a project that created a lot of interest, including from the people who wrote these papers. But these papers **ARE ABOUT** about matrix.org, element (previous new vector) and the people in charge of both. They are not about the community projects.

Happy to answer issues that remain on topic with the repo content.

**Comment by MTRNord** [comment]
> I have added [a notice](https://github.com/libremonde-org/paper-research-privacy-matrix.org/commit/dfae4dbb53e46ca26b17b1b1553c2d075e351c95) for people who still end up on those papers, making sure they use their own judgement to evaluate the accuracy of these papers and how well they pass the test of time.
> 
> As for your comments:
> ---
> > For example identity servers can be selfhosted these days and even aren't really needed anymore unless you want to search by phone number.
> 
> The papers never said they couldn't be self-hosted, only that people were led to believe they couldn't or didn't need to.   
> Search by phone number always has been the point of using them, thanks for confirming this is not outdated and still accurate.

Ah ok yes if that was the intent then it is true. The paper sounded like the point was that selfhosting them is overly hard plus it being always activated. Which both (imho) changed over the last few years :) 

> 
> ---
> 
> > Also the reference implementation keyword was dropped by both element (previously riot) and Synapse.
> 
> The paper is clear, section [Closing words](https://github.com/libremonde-org/paper-research-privacy-matrix.org/blob/master/part1/README.md#closing-words) of Part 1:
> > Matrix.org makes a promise of a secure and self-contained protocol while promoting privacy. But at the same time, has a near-monopol in the whole ecosystem in terms of client and server use: Riot and synapse, also labelled "reference implementations"
> 
> You can see a capture of the matrix.org website as of writing this reply ([Wayback Machine link for posterity](https://web.archive.org/web/20230410204653/https://matrix.org/)):
> ![image](https://user-images.githubusercontent.com/10545559/230995972-26bbd1f3-25c1-4e80-b1f2-0e0895856ca2.png)
> With the reference implementations link pointing to the matrix.org github repos:
> ![image](https://user-images.githubusercontent.com/10545559/230996061-2b822caf-701b-40f2-8df2-7f8b10abbb95.png)
> [Wayback machine](https://web.archive.org/web/20211102225440/https://matrix.org/) tells us nothing changed on the matrix.org website. Seems accurate enough to me.

Yeah the page is known to be outdated. It's in the process of being rewritten currently and is meant to be deployed in this year. They dropped the label "reference implementation" in their github repos though. 

> 
> ---
> 
> > Also not that matrix is far more diverse than matrix.org or element (previously new vector).
> > You can choose a community homeserver implementation (conduit or construct) and plenty of foss community made clients like nheko or fluffychat.
> 
> Correct, which was also true back then. Matrix has always been a project that created a lot of interest, including from the people who wrote these papers. But these papers **ARE ABOUT** about matrix.org, element (previous new vector) and the people in charge of both. They are not about the community projects.
> 
> Happy to answer issues that remain on topic with the repo content.

**Comment by maxidorius** [comment]
Glad to hear the front page might be updated! Hopefully it will allow less confusion on that front. I wish the papers were actually outdated but I guess we're not there yet.

Thank you for the feedback and for reading those papers!
